# Generated by Django 5.2.4 on 2026-06-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=124)),
                ("surname", models.CharField(max_length=124)),
                ("avatar", models.ImageField(blank=True, upload_to="avatars/")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                ("github_url", models.URLField(blank=True)),
                ("about", models.TextField(blank=True, max_length=256)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="interested_users",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
