--
-- PostgreSQL database dump
--

\restrict 8Lr9iyQqcJssDqGMjZaCiZr5kwIsrqT2XRAeLjoS0uY7bK40rP5oDDXdkK6GEDl

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: projects_project; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects_project (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    github_url character varying(200) NOT NULL,
    status character varying(6) NOT NULL,
    owner_id bigint NOT NULL
);


--
-- Name: projects_project_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.projects_project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects_project_participants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects_project_participants (
    id bigint NOT NULL,
    project_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: projects_project_participants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.projects_project_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_project_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    email character varying(254) NOT NULL,
    name character varying(124) NOT NULL,
    surname character varying(124) NOT NULL,
    avatar character varying(100) NOT NULL,
    phone character varying(12),
    github_url character varying(200) NOT NULL,
    about text NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL
);


--
-- Name: users_user_favorites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user_favorites (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    project_id bigint NOT NULL
);


--
-- Name: users_user_favorites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user_favorites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_favorites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add project	7	add_project
26	Can change project	7	change_project
27	Can delete project	7	delete_project
28	Can view project	7	view_project
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	users	user
7	projects	project
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	projects	0001_initial	2026-06-09 19:40:58.784036+00
2	users	0001_initial	2026-06-09 19:40:58.805505+00
3	contenttypes	0001_initial	2026-06-09 19:40:58.811171+00
4	admin	0001_initial	2026-06-09 19:40:58.825126+00
5	admin	0002_logentry_remove_auto_add	2026-06-09 19:40:58.828367+00
6	admin	0003_logentry_add_action_flag_choices	2026-06-09 19:40:58.83131+00
7	contenttypes	0002_remove_content_type_name	2026-06-09 19:40:58.837539+00
8	auth	0001_initial	2026-06-09 19:40:58.865794+00
9	auth	0002_alter_permission_name_max_length	2026-06-09 19:40:58.869694+00
10	auth	0003_alter_user_email_max_length	2026-06-09 19:40:58.872121+00
11	auth	0004_alter_user_username_opts	2026-06-09 19:40:58.874481+00
12	auth	0005_alter_user_last_login_null	2026-06-09 19:40:58.877886+00
13	auth	0006_require_contenttypes_0002	2026-06-09 19:40:58.878958+00
14	auth	0007_alter_validators_add_error_messages	2026-06-09 19:40:58.881471+00
15	auth	0008_alter_user_username_max_length	2026-06-09 19:40:58.885072+00
16	auth	0009_alter_user_last_name_max_length	2026-06-09 19:40:58.887891+00
17	auth	0010_alter_group_name_max_length	2026-06-09 19:40:58.892692+00
18	auth	0011_update_proxy_permissions	2026-06-09 19:40:58.896506+00
19	auth	0012_alter_user_first_name_max_length	2026-06-09 19:40:58.899136+00
20	projects	0002_initial	2026-06-09 19:40:58.912828+00
21	sessions	0001_initial	2026-06-09 19:40:58.91833+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
lw0o86sx9siru40ge9t77ikkpg9w4pcz	.eJxVjDsOwjAQBe_iGln-xR9Kes5g7dprHEC2FCcV4u4QKQW0b2bei0XY1hq3QUucMzszyU6_G0J6UNtBvkO7dZ56W5cZ-a7wgw5-7Zmel8P9O6gw6rdWMqMWVgZhncdiCpbJFzLSkcrWhqAFJluoTOBAgVDSmCx1Mt6DIkzs_QHcDjf8:1wX2RZ:fwEJXLFGZe_pHn_XpoyOtD4piidtTieWYc0QnBKPjSM	2026-06-23 19:49:01.818237+00
\.


--
-- Data for Name: projects_project; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.projects_project (id, name, description, created_at, github_url, status, owner_id) FROM stdin;
1	TaskFlow — менеджер задач	Простой и удобный таск-менеджер для небольших команд. Ищем фронтендера и дизайнера.	2026-06-09 19:45:20.716369+00	https://github.com/alice/taskflow	open	1
2	EcoMap — карта экомаршрутов	Интерактивная карта для велосипедистов и пешеходных маршрутов. Ищем бэкендера.	2026-06-09 19:45:20.726083+00	https://github.com/bob/ecomap	open	2
3	LangBuddy — изучение языков	Платформа для практики разговорного иностранного языка с носителями.	2026-06-09 19:45:20.728399+00		open	3
4	RetroGames Archive	Архив ретро-игр с возможностью играть прямо в браузере. Проект завершён.	2026-06-09 19:45:20.730569+00		closed	1
\.


--
-- Data for Name: projects_project_participants; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.projects_project_participants (id, project_id, user_id) FROM stdin;
1	1	2
2	2	3
3	3	1
\.


--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_user (id, password, last_login, email, name, surname, avatar, phone, github_url, about, is_active, is_staff) FROM stdin;
2	pbkdf2_sha256$1000000$t6ROsvL0an2OJBNh6Q0Wvc$C1M0+CNbLQEwk0Ew0h9DfSdW6e/aK6npuLxrr2iBX6k=	\N	bob@example.com	Борис	Иванов	avatars/avatar_277baa2b-8f98-425f-bc85-32ff7aceb8a5.png	\N	https://github.com/bob	Frontend-разработчик, React и TypeScript.	t	f
3	pbkdf2_sha256$1000000$Csc468SqNJwOsfiFCJpdjP$7IRgOtakRJ1ag+VSz3IsgrNA9VT1Wl37t4c2b9HwoUc=	\N	carol@example.com	Карина	Смирнова	avatars/avatar_a61d2071-93e7-493c-b38a-10c33dcb7a8e.png	\N		UI/UX дизайнер, Figma, прототипирование.	t	f
4	pbkdf2_sha256$1000000$qPSXQmHLjo0Nr1CPm9aR8M$3+NM7OLSBh2a+/eILRnMrIuRIiT/ad4E3dOCQXOhvGg=	\N	admin@example.com	Админ	Системный	avatars/avatar_797c4897-13c2-4d60-b054-698852669797.png	\N			t	t
5	pbkdf2_sha256$1000000$0DG8jL8COv2KusSn4NJ322$akd/tE+uGpjzVLeXaJwwHLlnKW+vvE/Mpnmzg4JSt9k=	\N	dmitry@example.com	Дмитрий	Козлов	avatars/avatar_21120e5d-1387-463b-b2f1-0c751fc3222e.png	\N	https://github.com/dmitry	Full-stack разработчик. Работаю с Vue.js и FastAPI.	t	f
6	pbkdf2_sha256$1000000$yNEmNR5ct4w3YQSBaEI7dr$4+MYPm161IO/vBM0XMkS9hsUnneQx50tBmx4IxISGGk=	\N	kate@example.com	Екатерина	Новикова	avatars/avatar_105fc8b9-4e84-4937-aa88-9876107a2af8.png	\N	https://github.com/kate	Data Scientist, ML-инженер. Люблю Python и sklearn.	t	f
7	pbkdf2_sha256$1000000$Zh3Ybc1Q5vW1Iq4ZAWnVbV$2LTqvkui5qGu6PvvMtkaeXuWVY+FbsI+r5EwvQrYinU=	\N	misha@example.com	Михаил	Соколов	avatars/avatar_d390c49f-80d2-40a8-a0e5-8dffc7d541df.png	\N		iOS разработчик, Swift. Открыт к новым проектам.	t	f
8	pbkdf2_sha256$1000000$CVte0vagFaKQdku3hx9dje$Z7K4DAFe/TUOW5tZFRG/p19aC6KdrwWwMb/3p8eO1bw=	\N	olga@example.com	Ольга	Лебедева	avatars/avatar_c5d62677-8275-4906-9d42-c4ecd8ca103e.png	\N	https://github.com/olga	DevOps инженер. Kubernetes, CI/CD, мониторинг.	t	f
9	pbkdf2_sha256$1000000$YqtlYWBR8dbS1b82XNBwDC$2I/3TStiNK5kgqZz6YLCtZkPZ9eka8K9q15tshVfeVw=	\N	andrey@example.com	Андрей	Волков	avatars/avatar_8afc0d1e-4363-487f-a4d3-4fea50d2e426.png	\N	https://github.com/andrey	Backend на Go и Rust. Интересуюсь highload.	t	f
10	pbkdf2_sha256$1000000$Azadv20jbfcvFMTcipvDgg$insR4CMmgeXOXeiK7JNOQ5nQ1mjfmIai6YZKgtyqqGs=	\N	natasha@example.com	Наталья	Морозова	avatars/avatar_7c45bf45-dca6-47f6-9d4c-7e4703493ad8.png	\N		UX/UI дизайнер, Figma, Adobe XD.	t	f
11	pbkdf2_sha256$1000000$0sx38QzWvS0JIbgztEXia8$hWR6+5OFO73/gkx/2h6sLfM8Qjz3vS7zbLMXJxItn3s=	\N	sergey@example.com	Сергей	Попов	avatars/avatar_7fe53d1f-5126-410c-bd86-aab7b0797223.png	\N	https://github.com/sergey	Android разработчик, Kotlin, Jetpack Compose.	t	f
12	pbkdf2_sha256$1000000$2RAYdZHOdOC5LEWNnyt2ES$52ROtYIdHdhNuyMO2PP2g73nHGsCwAAJ6VRZ78BjtnM=	\N	nastya@example.com	Анастасия	Федорова	avatars/avatar_ce6224d9-5185-4cf6-a621-572c860e65fc.png	\N	https://github.com/nastya	Фронтенд, React, TypeScript. Люблю анимации.	t	f
1	pbkdf2_sha256$1000000$8vMhmXfOOtCZvNtnmWnAHh$0yYYHcC0lgC7tS9jltk5kBzVM13U9QG/Idfh1gE/jXk=	2026-06-09 19:49:01.816319+00	alice@example.com	Алиса	Петрова	avatars/avatar_d65f2891-3005-4f46-a2e6-b28efc3450ae.png	\N	https://github.com/alice	Backend-разработчик, люблю Python и Django.	t	f
\.


--
-- Data for Name: users_user_favorites; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_user_favorites (id, user_id, project_id) FROM stdin;
1	1	2
2	2	1
3	2	3
4	3	1
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 28, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 7, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 21, true);


--
-- Name: projects_project_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.projects_project_id_seq', 4, true);


--
-- Name: projects_project_participants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.projects_project_participants_id_seq', 3, true);


--
-- Name: users_user_favorites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_user_favorites_id_seq', 4, true);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_user_id_seq', 12, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: projects_project_participants projects_project_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects_project_participants
    ADD CONSTRAINT projects_project_participants_pkey PRIMARY KEY (id);


--
-- Name: projects_project_participants projects_project_participants_project_id_user_id_64171833_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects_project_participants
    ADD CONSTRAINT projects_project_participants_project_id_user_id_64171833_uniq UNIQUE (project_id, user_id);


--
-- Name: projects_project projects_project_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- Name: users_user_favorites users_user_favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_favorites
    ADD CONSTRAINT users_user_favorites_pkey PRIMARY KEY (id);


--
-- Name: users_user_favorites users_user_favorites_user_id_project_id_64f30546_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_favorites
    ADD CONSTRAINT users_user_favorites_user_id_project_id_64f30546_uniq UNIQUE (user_id, project_id);


--
-- Name: users_user users_user_phone_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_phone_key UNIQUE (phone);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: projects_project_owner_id_b940de39; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX projects_project_owner_id_b940de39 ON public.projects_project USING btree (owner_id);


--
-- Name: projects_project_participants_project_id_977bbd69; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX projects_project_participants_project_id_977bbd69 ON public.projects_project_participants USING btree (project_id);


--
-- Name: projects_project_participants_user_id_5905fe7e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX projects_project_participants_user_id_5905fe7e ON public.projects_project_participants USING btree (user_id);


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_favorites_project_id_9f10812e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_favorites_project_id_9f10812e ON public.users_user_favorites USING btree (project_id);


--
-- Name: users_user_favorites_user_id_fcff1f9e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_favorites_user_id_fcff1f9e ON public.users_user_favorites USING btree (user_id);


--
-- Name: users_user_phone_fe37f55c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_phone_fe37f55c_like ON public.users_user USING btree (phone varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_project projects_project_owner_id_b940de39_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_owner_id_b940de39_fk_users_user_id FOREIGN KEY (owner_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_project_participants projects_project_par_project_id_977bbd69_fk_projects_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects_project_participants
    ADD CONSTRAINT projects_project_par_project_id_977bbd69_fk_projects_ FOREIGN KEY (project_id) REFERENCES public.projects_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_project_participants projects_project_participants_user_id_5905fe7e_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects_project_participants
    ADD CONSTRAINT projects_project_participants_user_id_5905fe7e_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_favorites users_user_favorites_project_id_9f10812e_fk_projects_project_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_favorites
    ADD CONSTRAINT users_user_favorites_project_id_9f10812e_fk_projects_project_id FOREIGN KEY (project_id) REFERENCES public.projects_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_favorites users_user_favorites_user_id_fcff1f9e_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_favorites
    ADD CONSTRAINT users_user_favorites_user_id_fcff1f9e_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 8Lr9iyQqcJssDqGMjZaCiZr5kwIsrqT2XRAeLjoS0uY7bK40rP5oDDXdkK6GEDl

